/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ttms.ui;

import com.ttms.controller.commonConstants;
import com.ttms.controller.commonController;
import com.ttms.controller.lecturerController;
import com.ttms.controller.lecturerUnavailabilityController;
import com.ttms.model.DataObject;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class manageLecturerUnavailability extends javax.swing.JFrame {
    public manageLecturerUnavailability() {
        initComponents();
        loadLecturerDataObjectToComboBox();
        loadDataToTable();
    }

    private void clearAll() {
        txtDetail.setText("");
        calUnavDate.setDate(null);
        comboLecturerDataObjects.setSelectedIndex(0);
    }

    private void loadLecturerDataObjectToComboBox() {
        try {
            String[] columnList = {"lecturer_id", "lecturer_title", "lecturer_name", "lecturer_email", "lecturer_contact_no", "lecturer_detail", "lecturer_status"};
            ResultSet rset = lecturerController.getAllLecturers();
            commonController.loadDataObjectsIntoComboBox(comboLecturerDataObjects, rset, columnList, "lecturer_name");
        } catch (SQLException ex) {
            Logger.getLogger(manageLecturerUnavailability.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void addLecturerUnavailabilityDetails() {
        if (calUnavDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select date !", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int option = JOptionPane.showConfirmDialog(this, "Correct all data entered ?");
        if (option == JOptionPane.YES_OPTION) {
            try {
                DataObject dataObj = (DataObject) comboLecturerDataObjects.getSelectedItem();
                int lecturerId = commonController.getIntOrZeroFromString(dataObj.get("lecturer_id"));
                String fromTimeString = comboFromHours.getSelectedItem().toString() + ":" + comboFromMinutes.getSelectedItem().toString() + ":" + "00";
                String toTimeString = comboToHours.getSelectedItem().toString() + ":" + comboToMinutes.getSelectedItem().toString() + ":" + "00";

                boolean status = lecturerUnavailabilityController.addLecturerUnavailability(lecturerId,
                        commonController.getMysqlDateFromJDateChooser(calUnavDate), fromTimeString,
                        toTimeString, txtDetail.getText().trim());

                if (status) {
                    JOptionPane.showMessageDialog(this, "Record added successfully !", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(manageLecturerUnavailability.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void loadDataToTable() {
        try {
            ResultSet rset = lecturerUnavailabilityController.getLecUnavaDetailsWithJoinQuery();
            String[] columnList = {"lecturer_availablity_id", "lecturer_name", "lecturer_availablity_unavailable_date",
                "lecturer_availablity_unavailable_time_from", "lecturer_availablity_unavailable_time_to", "lecturer_availablity_detail"};
            commonController.loadDataToTable(tblLecturerUnavailableDetails, rset, columnList);
        } catch (SQLException ex) {
            Logger.getLogger(manageLecturerUnavailability.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchLecAvaiByLecName(String searchByLecName) {
        try {
            ResultSet rset = lecturerUnavailabilityController.getAvailableLectureByOneAttributeWithJoinQuery("lecturer_name",
                    commonConstants.Sql.LIKE, "%" + searchByLecName + "%");
            String[] columnList = {"lecturer_availablity_id", "lecturer_name", "lecturer_availablity_unavailable_date",
                "lecturer_availablity_unavailable_time_from", "lecturer_availablity_unavailable_time_to", "lecturer_availablity_detail"};
            commonController.loadDataToTable(tblLecturerUnavailableDetails, rset, columnList);
        } catch (SQLException ex) {
            Logger.getLogger(manageLecturerUnavailability.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLecturerUnavailableDetails = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtDetail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboLecturerDataObjects = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboFromMinutes = new javax.swing.JComboBox<>();
        comboFromHours = new javax.swing.JComboBox<>();
        comboToHours = new javax.swing.JComboBox<>();
        comboToMinutes = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        calUnavDate = new com.toedter.calendar.JDateChooser();
        txtSearchLecUnavailability = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lecturer Unavailability");
        setMaximumSize(new java.awt.Dimension(1269, 643));
        setMinimumSize(new java.awt.Dimension(1269, 643));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1340, 643));
        jPanel1.setMinimumSize(new java.awt.Dimension(1340, 643));
        jPanel1.setPreferredSize(new java.awt.Dimension(1340, 643));

        tblLecturerUnavailableDetails.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tblLecturerUnavailableDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "availabilityId", "Lecturer Name", "Date", "From Time", "To Time ", "Detail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLecturerUnavailableDetails.setRowHeight(20);
        tblLecturerUnavailableDetails.setRowMargin(2);
        tblLecturerUnavailableDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblLecturerUnavailableDetails);
        if (tblLecturerUnavailableDetails.getColumnModel().getColumnCount() > 0) {
            tblLecturerUnavailableDetails.getColumnModel().getColumn(0).setMinWidth(0);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(0).setMaxWidth(0);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(1).setResizable(false);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(2).setMinWidth(120);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(2).setPreferredWidth(120);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(2).setMaxWidth(120);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(3).setMinWidth(120);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(3).setMaxWidth(120);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(4).setMinWidth(120);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(4).setMaxWidth(120);
            tblLecturerUnavailableDetails.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtDetail.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtDetail.setToolTipText("Details / Remarks");
        txtDetail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtDetail.setSelectionColor(new java.awt.Color(255, 255, 0));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ttms/lableIcons/Year.png"))); // NOI18N
        jLabel2.setToolTipText("Unavailable Date");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ttms/lableIcons/Time_From.png"))); // NOI18N
        jLabel3.setToolTipText("Unavialable Time [From]");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ttms/lableIcons/Detail.png"))); // NOI18N
        jLabel4.setToolTipText("Details / Remarks");

        comboLecturerDataObjects.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        comboLecturerDataObjects.setToolTipText("Lecturer Name");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ttms/lableIcons/Lecturer.png"))); // NOI18N
        jLabel5.setToolTipText("Lecturer Name");

        btSave.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ttms/labelIcons2/saveIcon_green.png"))); // NOI18N
        btSave.setToolTipText("Add Lecturer Unavailability Details");
        btSave.setBorder(null);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ttms/lableIcons/Time_To.png"))); // NOI18N
        jLabel6.setToolTipText("Unavialable Time [To]");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comboFromMinutes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        comboFromMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "10", "20", "30", "40", "50" }));
        comboFromMinutes.setToolTipText("Unavialable Time [From]");
        comboFromMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFromMinutesActionPerformed(evt);
            }
        });

        comboFromHours.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        comboFromHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        comboFromHours.setToolTipText("Unavialable Time [From]");
        comboFromHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFromHoursActionPerformed(evt);
            }
        });

        comboToHours.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        comboToHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        comboToHours.setToolTipText("Unavialable Time [To]");
        comboToHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboToHoursActionPerformed(evt);
            }
        });

        comboToMinutes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        comboToMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "10", "20", "30", "40", "50" }));
        comboToMinutes.setToolTipText("Unavialable Time [To]");
        comboToMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboToMinutesActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Unavailability Details / Remarks");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Unavailable Date");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Lecturer Name");

        calUnavDate.setToolTipText("Unavailable Date");
        calUnavDate.setFocusCycleRoot(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calUnavDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboLecturerDataObjects, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDetail)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboToHours, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboToMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSave, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboFromHours, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboFromMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLecturerDataObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calUnavDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboFromHours, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboFromMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboToHours, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboToMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        txtSearchLecUnavailability.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtSearchLecUnavailability.setToolTipText("Search by Lecturer name");
        txtSearchLecUnavailability.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtSearchLecUnavailability.setSelectionColor(new java.awt.Color(255, 255, 0));
        txtSearchLecUnavailability.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchLecUnavailabilityKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchLecUnavailability, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSearchLecUnavailability, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        addLecturerUnavailabilityDetails();
        clearAll();
        loadDataToTable();
    }//GEN-LAST:event_btSaveActionPerformed

    private void comboFromMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFromMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFromMinutesActionPerformed

    private void comboFromHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFromHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFromHoursActionPerformed

    private void comboToHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboToHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboToHoursActionPerformed

    private void comboToMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboToMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboToMinutesActionPerformed

    private void txtSearchLecUnavailabilityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchLecUnavailabilityKeyReleased
        searchLecAvaiByLecName(txtSearchLecUnavailability.getText().trim());
    }//GEN-LAST:event_txtSearchLecUnavailabilityKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageLecturerUnavailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageLecturerUnavailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageLecturerUnavailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageLecturerUnavailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageLecturerUnavailability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private com.toedter.calendar.JDateChooser calUnavDate;
    private javax.swing.JComboBox<String> comboFromHours;
    private javax.swing.JComboBox<String> comboFromMinutes;
    private javax.swing.JComboBox<String> comboLecturerDataObjects;
    private javax.swing.JComboBox<String> comboToHours;
    private javax.swing.JComboBox<String> comboToMinutes;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLecturerUnavailableDetails;
    private javax.swing.JTextField txtDetail;
    private javax.swing.JTextField txtSearchLecUnavailability;
    // End of variables declaration//GEN-END:variables
}
